# Generated by Django 4.0.6 on 2022-07-30 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40, verbose_name='Тип заявки')),
            ],
            options={
                'verbose_name': 'Тип заявки',
                'verbose_name_plural': 'Типы заявки',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('organization_name', models.TextField(max_length=255, verbose_name='Наименование организации')),
                ('applicant', models.TextField(max_length=255, verbose_name='Заявитель')),
                ('priority', models.CharField(choices=[('LO', 'Низкий'), ('ME', 'Средний'), ('HI', 'Высокий')], default='ME', max_length=2, verbose_name='Уровень приоритета')),
                ('ticket_name', models.CharField(max_length=255, verbose_name='Наименование заявки')),
                ('status', models.CharField(choices=[('RE', 'Отказано'), ('AC', 'Принято'), ('EX', 'Исполнено')], default='AC', max_length=2, verbose_name='Статус заявки')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.typeticket', verbose_name='Тип заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
